### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by itdog1973**
晚安老師，我Discord name 是Jason Ko
第二週作業完成了，以下是我專案的網址
http://18.180.240.36:3000/

不過我有一個問題關於在我的static/main.js裡的第10行的那一段code, 我不理解為什麼我只要把這行code拿掉我的第77行code就出狀況，結果畫面出不來。第10行code只是為簡單為我html element設定一個id,而我在後面都沒有過這id，可是拿掉就沒法跑。懇請老師指點一些提示。謝謝

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Your aspect ratio of images are broken and layout exceed screen width in small and middle screen size. (<1200px)
2. Your wrap declared as a local variable, so code in line 77 cannot access it. But if you have an element with id, JavaScript let you use id in code to access this element.

未命名-6

**Comment by itdog1973** [comment]
I see, very help !
I will go to fix both issue and send you another PR .
Thanks Peng Peng,

**Comment by itdog1973** [comment]
HI Peng Peng, I have added 2 commit on the change of the project and added some comment in the js code. Could you please have a look and if it is possible could you tell me if there is anything that I can do better in this assignment. Thanks a bunch !

**Comment by itdog1973** [comment]
> As described above, your aspect ratio of images are broken in small and middle screen size. (<1200px)

i have already fixed it, is the aspect ratio of images still broken?

**Comment by cwpeng** [comment]
It's still broken from my view for now. Maybe, you could paste screenshot from your view.

**Comment by itdog1973** [comment]
> It's still broken from my view for now. Maybe, you could paste screenshot from your view.

Sounds good! I've added a video demo of the RWD on my README. I would also like to attach the demo link here. Please feel free to have a look. Thank you so much!

https://www.youtube.com/watch?v=1Y6M50isry4

**Comment by cwpeng** [comment]
Based on your video demo. Aspect ratio of images (圖片的長寬比例) is indeed broken. (different from original image). If you still cannot get point, feel free to talk/message to me.

**Comment by itdog1973** [comment]
> Based on your video demo. Aspect ratio of images (圖片的長寬比例) is indeed broken. (different from original image). If you still cannot get point, feel free to talk/message to me.

I think I got your point, the previous images that on the website do not automatically adjust their size to fit the picture boxes along with the screen width changing. I have made a change on that. And, the change is already update on the website and please have a look :D 
 http://18.180.240.36:3000/
 Thanks a bunch!

**Comment by cwpeng** [comment]
Better, but the same issue remains in your key visual ( 中正紀念堂 ).

**Comment by itdog1973** [comment]
> Better, but the same issue remains in your key visual ( 中正紀念堂 ).

I have resized the item container and removed some unnecessary css code in RWD design .

http://18.180.240.36:3000/

Could you see if it is good now?

Thanks so much!

**Comment by itdog1973** [comment]
> Better, but the same issue remains in your key visual ( 中正紀念堂 ).

I have changed the the aspect ratio regarding the key visual. Could you please have a look?

Thanks a bunch!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by itdog1973** [comment]
> OK. Done.

yeah! Thank you

**Pull request merged**
